.TH "conn.php" 3 "Fri Jun 25 2021" "Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conn.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$host\fP = 'localhost'"
.br
.RI "Przypisanie zmiennym danych niezbędnych do połączenia z DB\&. "
.ti -1c
.RI "\fB$db_user\fP = 'root'"
.br
.ti -1c
.RI "\fB$db_password\fP =''"
.br
.ti -1c
.RI "\fB$db_name\fP = 'projekt'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$db_name = 'projekt'"

.PP
Definition at line 6 of file conn\&.php\&.
.SS "$db_password =''"

.PP
Definition at line 5 of file conn\&.php\&.
.SS "$db_user = 'root'"

.PP
Definition at line 4 of file conn\&.php\&.
.SS "$host = 'localhost'"

.PP
Przypisanie zmiennym danych niezbędnych do połączenia z DB\&. 
.PP
Definition at line 3 of file conn\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Project from the source code\&.
