.TH "main.php" 3 "Fri Jun 25 2021" "Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP (!isset( $_SESSION[ 'logged']))"
.br
.RI "Sprawdzenie czy po przejściu na stronę user jest zalogowany\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "if(!isset($_SESSION['logged']))"

.PP
Sprawdzenie czy po przejściu na stronę user jest zalogowany\&. 
.PP
Definition at line 4 of file main\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Project from the source code\&.
