.TH "welcome.php" 3 "Fri Jun 25 2021" "Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
welcome.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP(!isset($_SESSION['regcompleted'])) \fBelse\fP"
.br
.RI "Warunek sprawdzający czy zmienna sesyjna nie jest ustawiona\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBif\fP (!isset( $_SESSION[ 'regcompleted'])) else"
\fBInitial value:\fP
.PP
.nf
{
        unset($_SESSION['regcompleted'])
.fi
.PP
Warunek sprawdzający czy zmienna sesyjna nie jest ustawiona\&. 
.PP
Definition at line 11 of file welcome\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Project from the source code\&.
